currencies:
- currency: GBP
  symbol: USD
- currency: CHF
  symbol: USD
- currency: JPY
  symbol: USD
funds:
- code: '501018'
  name: 南方原油
  category: 原油
  holdings:
    equity_ratio: 82.66
    cash_ratio: 17.34
  holdings_portfolio: []
  future_hedging:
  - symbol: MCL
    delivery_month: '2604'
    weight: 100.0
    beta: 0.85
    currency: USD
    exchange: SMART
    name: 微原油期货
  valuation_portfolio:
  - symbol: USO
    weight: 62.69
    anchor: US
  - symbol: USO-EU
    weight: 37.31
    anchor: EU
  trade_etf: USO
  trade_future: MCL
  position: 82.66
- code: '160723'
  name: 嘉实原油
  category: 原油
  holdings:
    equity_ratio: 82.39
    cash_ratio: 17.61
  holdings_portfolio:
  - symbol: USO
    weight: 17.22
    currency: USD
    exchange: LSE
    name: United States Oil  Fund LP
  - symbol: BNO
    weight: 14.74
    currency: USD
    exchange: LSE
    name: United States Brent Oil Fund LP
  - symbol: 1671.T
    weight: 15.03
    currency: JPY
    exchange: TSEJ
    name: Simplex WTI ETF
  - symbol: 1699.T
    weight: 14.29
    currency: JPY
    exchange: TSEJ
    name: NEXT FUNDS NOMURA Crude Oil Long Index Linked Exchange Traded
  - symbol: BRNT.L
    weight: 14.89
    currency: USD
    exchange: LSE
    name: WisdomTree Brent Crude Oil
  - symbol: CRUD.L
    weight: 16.92
    currency: USD
    exchange: LSE
    name: WisdomTree WTI Crude Oil
  - symbol: BRNB.L
    weight: 0.25
    currency: USD
    exchange: LSE
    name: WisdomTree Bloomberg Brent Crude Oil
  future_hedging:
  - symbol: MCL
    delivery_month: '2604'
    weight: 100.0
    beta: 0.85
    currency: USD
    exchange: SMART
    name: 微原油期货
  valuation_portfolio:
  - symbol: USO
    weight: 78.43
    anchor: US
  - symbol: USO-EU
    weight: 21.57
    anchor: EU
  trade_etf: USO
  trade_future: MCL
  position: 82.39
- code: '161129'
  name: 易方达原油
  category: 原油
  holdings:
    equity_ratio: 84.99
    cash_ratio: 15.01
  holdings_portfolio:
  - symbol: CRUD.L
    weight: 18.52
    currency: USD
    exchange: LSE
    name: WisdomTree WTI Crude Oil
  - symbol: BRNB.L
    weight: 18.35
    currency: USD
    exchange: LSE
    name: WisdomTree Brent Crude Oil
  - symbol: DBO
    weight: 17.57
    currency: JPY
    exchange: TSEJ
    name: Investco DB OIL fund
  - symbol: 1671.T
    weight: 16.51
    currency: JPY
    exchange: TSEJ
    name: Simplex WTI ETF
  - symbol: 1699.T
    weight: 16.11
    currency: USD
    exchange: LSE
    name: NEXT FUNDS NOMURA Crude OilL
  - symbol: 03175.HK
    weight: 5.72
    currency: USD
    exchange: LSE
    name: samsung SP GSCI crude OIL  future
  future_hedging:
  - symbol: MCL
    delivery_month: '2604'
    weight: 100.0
    beta: 0.85
    currency: USD
    exchange: SMART
    name: 微原油期货
  valuation_portfolio:
  - symbol: USO
    weight: 68.86
    anchor: US
  - symbol: USO-EU
    weight: 31.14
    anchor: EU
  trade_etf: USO
  trade_future: MCL
  position: 84.99
- code: '160216'
  name: 国泰大宗商品
  category: 黄金
  trade_etf: GLD,USO
  trade_future: ''
  holdings:
    equity_ratio: 65.12
    cash_ratio: 34.88
  valuation_portfolio:
  - symbol: SLV
    weight: 63.25
    anchor: US
  - symbol: USO
    weight: 36.75
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 65.12
- code: '161815'
  name: 银华抗通胀
  category: 黄金
  trade_etf: GLD,USO
  trade_future: ''
  holdings:
    equity_ratio: 74.14
    cash_ratio: 25.86
  valuation_portfolio:
  - symbol: GLD
    weight: 53.72
    anchor: US
  - symbol: USO-EU
    weight: 28.31
    anchor: EU
  - symbol: USO
    weight: 17.97
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging:
  - symbol: GC
    delivery_month: '2606'
    weight: 75.0
    currency: USD
    exchange: SMART
    name: 黄金
  - symbol: CL
    delivery_month: '2605'
    weight: 25.0
    currency: USD
    exchange: SMART
    name: 原油
  position: 74.14
- code: '160719'
  name: 嘉实黄金
  category: 黄金
  holdings:
    equity_ratio: 96.05
    cash_ratio: 3.95
  holdings_portfolio:
  - symbol: GLD
    weight: 19.02
    currency: USD
    exchange: LSE
    name: SPDR黄金
  - symbol: SGOL
    weight: 18.99
    currency: USD
    exchange: LSE
    name: abrdn黄金
  - symbol: IAU
    weight: 18.72
    currency: USD
    exchange: LSE
    name: iShares黄金
  - symbol: ZGLD
    weight: 16.69
    currency: CHF
    exchange: SMART
    name: Swisscanto
  - symbol: AUUSI.sw
    weight: 16.33
    currency: USD
    exchange: LSE
    name: 瑞银黄金
  - symbol: CSGLDC
    weight: 10.26
    currency: CHF
    exchange: SMART
    name: iShares瑞士
  future_hedging:
  - symbol: MGC
    delivery_month: '2604'
    weight: 100.0
    beta: 1.0
    currency: USD
    exchange: SMART
    name: ''
  valuation_portfolio:
  - symbol: GLD
    weight: 53.82
    anchor: US
  - symbol: GLD-EU
    weight: 46.18
    anchor: EU
  trade_etf: GLD
  trade_future: MGC
  position: 96.05
- code: '161116'
  name: 易方达黄金
  category: 黄金
  trade_etf: GLD
  trade_future: MGC
  holdings:
    equity_ratio: 93.78
    cash_ratio: 6.22
  valuation_portfolio:
  - symbol: GLD
    weight: 82.21
    anchor: US
  - symbol: GLD-EU
    weight: 17.79
    anchor: EU
  sina_index_url: ''
  holdings_portfolio:
  - symbol: GLD
    weight: 20.09
    currency: USD
    exchange: LSE
    name: SPDR
  - symbol: SGOL
    weight: 19.42
    currency: USD
    exchange: LSE
    name: abrdn Physical
  - symbol: UGL
    weight: 19.07
    currency: USD
    exchange: LSE
    name: 'Proshare Ultra2倍做多 '
  - symbol: GLDM
    weight: 14.73
    currency: USD
    exchange: LSE
    name: SPDR Gold MiniShares Trust
  - symbol: IAU
    weight: 13.94
    currency: USD
    exchange: LSE
    name: 'Ishare Gold Trust '
  - symbol: AUUSI.sw
    weight: 12.75
    currency: CHF
    exchange: SMART
    name: 'UBS ETF '
  future_hedging:
  - symbol: MGC
    delivery_month: '2604'
    weight: 100.0
    currency: USD
    exchange: SMART
    name: ''
  position: 93.78
- code: '164701'
  name: 汇添富贵金属
  category: 黄金
  holdings:
    equity_ratio: 99.75
    cash_ratio: 0.25
  holdings_portfolio:
  - symbol: UGL
    weight: 33.165
    currency: USD
    exchange: LSE
    name: 'Proshare Ultra2倍做多 '
  - symbol: GLDM
    weight: 13.5876
    currency: USD
    exchange: LSE
    name: 'SPDR miniShares Trust '
  - symbol: IAUM
    weight: 12.9256
    currency: USD
    exchange: LSE
    name: ishares Gold Trust Micro
  - symbol: GLD
    weight: 10.0
    currency: USD
    exchange: LSE
    name: 'SPDR '
  - symbol: BAR
    weight: 9.95
    currency: USD
    exchange: LSE
    name: Granitrshares Trust
  - symbol: AAAU
    weight: 7.79
    currency: USD
    exchange: LSE
    name: 高盛 physical Gold
  - symbol: SGOL
    weight: 6.45
    currency: USD
    exchange: LSE
    name: abrdn Physical
  - symbol: IAU
    weight: 4.82
    currency: USD
    exchange: LSE
    name: ishare Gold trust
  - symbol: SLV
    weight: 1.15
    currency: USD
    exchange: LSE
    name: ishares Silver Trust
  - symbol: SIVR
    weight: 0.16
    currency: USD
    exchange: LSE
    name: abrdn Physical silver
  future_hedging:
  - symbol: MGC
    delivery_month: '2604'
    weight: 100.0
    beta: 1.0
    currency: USD
    exchange: SMART
    name: ''
  valuation_portfolio:
  - symbol: GLD
    weight: 99.96
    anchor: US
  - symbol: SLV
    weight: 0.04
    anchor: US
  trade_etf: GLD
  trade_future: MGC
  position: 99.75
- code: '165513'
  name: 中信保诚
  category: 黄金
  holdings:
    equity_ratio: 90.82
    cash_ratio: 9.18
  holdings_portfolio: []
  future_hedging:
  - symbol: MGC
    delivery_month: ''
    weight: 100.0
    beta: 1.0
    currency: USD
    exchange: SMART
    name: ''
  valuation_portfolio:
  - symbol: GLD
    weight: 94.89
    anchor: US
  - symbol: GLD-EU
    weight: 5.11
    anchor: EU
  trade_etf: GLD
  trade_future: MGC
  position: 90.82
- code: '513350'
  name: 富国标普石油
  category: 纯ETF
  trade_etf: XOP
  trade_future: ''
  holdings:
    equity_ratio: 100.0
    cash_ratio: 0.0
  valuation_portfolio:
  - symbol: XOP
    weight: 100.0
    anchor: US
    name: 人民币在岸价
    currency: USD
    exchange: SMART
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  val_tab_type: sector
  rate_type: spot
- code: '159518'
  name: 嘉实标普石油
  category: 纯ETF
  trade_etf: XOP
  trade_future: ''
  holdings:
    equity_ratio: 100.0
    cash_ratio: 0.0
  valuation_portfolio:
  - symbol: XOP
    weight: 100.0
    anchor: US
    name: 人民币在岸价
    currency: USD
    exchange: SMART
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  rate_type: spot
- code: '162411'
  name: 华宝油气
  category: 纯ETF
  trade_etf: XOP
  trade_future: ''
  holdings:
    equity_ratio: 95.0
    cash_ratio: 5.0
  valuation_portfolio:
  - symbol: XOP
    weight: 100.0
    anchor: US
    name: 准确应该用净值，基本无溢价
    currency: USD
    exchange: SMART
  sina_index_url: ''
  holdings_portfolio:
  - symbol: XOP
    weight: 100.0
    currency: USD
    exchange: LSE
    name: ''
  future_hedging: []
  position: 95.0
- code: '162415'
  name: 美国消费
  category: 纯ETF
  trade_etf: XLY
  trade_future: ''
  holdings:
    equity_ratio: 94.0
    cash_ratio: 6.0
  valuation_portfolio:
  - symbol: XLY
    weight: 100.0
    anchor: US
    name: SPDR可选消费品ETF
    currency: USD
    exchange: SMART
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
- code: '159502'
  name: 嘉实标普生物
  category: 纯ETF
  trade_etf: XBI
  trade_future: ''
  holdings:
    equity_ratio: 99.0
    cash_ratio: 1.0
  valuation_portfolio:
  - symbol: XBI
    weight: 100.0
    anchor: US
    name: 人民币在岸价
    currency: USD
    exchange: SMART
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  val_tab_type: sector
  rate_type: spot
  position: 99.0
- code: '161127'
  name: 标普生物科技
  category: 纯ETF
  trade_etf: XBI
  trade_future: ''
  holdings:
    equity_ratio: 95.0
    cash_ratio: 5.0
  valuation_portfolio:
  - symbol: XBI
    weight: 100.0
    anchor: US
    name: 准确应该用净值，基本无溢价
    currency: USD
    exchange: SMART
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 95.0
- code: '161125'
  name: 易方达标普500
  category: 指数
  trade_etf: SPY
  trade_future: MES
  holdings:
    equity_ratio: 95.0
    cash_ratio: 5.0
  valuation_portfolio:
  - symbol: SPY
    weight: 100.0
    anchor: US
    name: 美股收盘
    currency: USD
    exchange: SMART
  sina_index_url: https://stock.finance.sina.com.cn/usstock/quotes/.INX.html
  holdings_portfolio: []
  future_hedging:
  - symbol: MES
    delivery_month: '2604'
    weight: 100.0
    currency: USD
    exchange: SMART
    name: 表明普 500 指数微型期货（Micro E-mini S&P 500
  position: 95.0
- code: '161130'
  name: 易方达纳100
  category: 指数
  trade_etf: QQQ
  trade_future: MNQ
  holdings:
    equity_ratio: 95.0
    cash_ratio: 5.0
  valuation_portfolio:
  - symbol: QQQ
    weight: 100.0
    anchor: US
    name: 美股收盘
    currency: USD
    exchange: SMART
  sina_index_url: https://stock.finance.sina.com.cn/usstock/quotes/.NDX.html
  holdings_portfolio: []
  future_hedging:
  - symbol: MNQ
    delivery_month: '2604'
    weight: 100.0
    currency: USD
    exchange: SMART
    name: 微型纳斯达克100指数期货
  position: 95.0
- code: '164824'
  name: 交银印度
  category: 纯ETF
  trade_etf: INDA
  trade_future: ''
  holdings:
    equity_ratio: 89.17
    cash_ratio: 10.83
  valuation_portfolio:
  - symbol: INDA
    weight: 59.4
    anchor: US
  - symbol: INDA-EU
    weight: 34.78
    anchor: EU
  - symbol: INDA-JP
    weight: 4.84
    anchor: JP
  - symbol: INDA-HK
    weight: 0.98
    anchor: HK
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 89.17
- code: '164906'
  name: 交银中证海外
  category: 纯ETF
  trade_etf: KWEB
  trade_future: ''
  holdings:
    equity_ratio: 92.0
    cash_ratio: 8.0
  valuation_portfolio:
  - symbol: KWEB
    weight: 100.0
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 92.0
- code: '161126'
  name: 标普医疗保健
  category: 纯ETF
  trade_etf: RSPH
  trade_future: ''
  holdings:
    equity_ratio: 95.0
    cash_ratio: 5.0
  valuation_portfolio:
  - symbol: RSPH
    weight: 100.0
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 95.0
- code: '163208'
  name: 诺安油气能源
  category: 黄金原油
  trade_etf: XLE
  trade_future: ''
  holdings:
    equity_ratio: 90.77
    cash_ratio: 9.23
  valuation_portfolio:
  - symbol: XLE
    weight: 86.72
    anchor: US
  - symbol: USO
    weight: 13.28
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 90.77
- code: '160644'
  name: 港美互联网
  category: 混合跨境
  trade_etf: ''
  trade_future: ''
  holdings:
    equity_ratio: 76.0
    cash_ratio: 24.0
  valuation_portfolio:
  - symbol: TSM
    weight: 14.79
    anchor: US
  - symbol: NVDA
    weight: 14.73
    anchor: US
  - symbol: SNDK
    weight: 13.94
    anchor: US
  - symbol: MU
    weight: 12.19
    anchor: US
  - symbol: '00700'
    weight: 10.71
    anchor: HK
  - symbol: GOOGL
    weight: 9.26
    anchor: US
  - symbol: 09988
    weight: 7.63
    anchor: US
  - symbol: 00883
    weight: 6.44
    anchor: US
  - symbol: AVGO
    weight: 5.68
    anchor: US
  - symbol: ASML
    weight: 4.64
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 76.0
- code: '501225'
  name: 顺丰半导体芯片
  category: 混合跨境
  trade_etf: SOXX
  trade_future: ''
  holdings:
    equity_ratio: 89.38
    cash_ratio: 10.62
  valuation_portfolio:
  - symbol: SOXX
    weight: 77.09
    anchor: US
  - symbol: SZ159560
    weight: 22.91
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 89.38
- code: '501312'
  name: 海外科技
  category: 混合跨境
  trade_etf: ''
  trade_future: ''
  holdings:
    equity_ratio: 80.0
    cash_ratio: 20.0
  valuation_portfolio:
  - symbol: ARKK
    weight: 20.85
    anchor: US
  - symbol: ARKG
    weight: 17.08
    anchor: US
  - symbol: ARKQ
    weight: 12.9
    anchor: US
  - symbol: SOXX
    weight: 10.58
    anchor: US
  - symbol: AIQ
    weight: 8.74
    anchor: US
  - symbol: QQQ
    weight: 8.29
    anchor: US
  - symbol: BOTZ
    weight: 8.28
    anchor: US
  - symbol: XLK
    weight: 7.17
    anchor: US
  - symbol: SMH
    weight: 4.77
    anchor: US
  - symbol: FINX
    weight: 1.34
    anchor: US
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging: []
  position: 80.0
- code: '161226'
  name: 国瑞白银期货
  category: 其他
  trade_etf: ''
  trade_future: 沪银Ag
  holdings:
    equity_ratio: 100.0
    cash_ratio: 0.0
  valuation_portfolio: []
  sina_index_url: ''
  holdings_portfolio: []
  future_hedging:
  - symbol: 沪银Ag
    delivery_month: '2604'
    weight: 100.0
    currency: USD
    exchange: SMART
    name: 上海期货交易所主连
last_update_date: '2026-04-07'
future_gold_calibration: .nan
future_oil_calibration: .nan
last_calibration_date: '2026-04-07'
last_futures_settlement_date: '2026-04-07'
162411_calibration: 1286.870785
161127_calibration: 505.047471
161125_calibration: 16399.583345
161130_calibration: 44691.210786
